Dz3
valvw/2024-2-VK-EDU-Frontend-V-Tuchinskaya pull request #3
Opened 2024-10-07 16:12 UTC by valvw

# Домашнее задание №3

Прошу @martinkomitsky, @haseprogram, @kgrechin или @uskov-anton проверить его.

Что было сделано:

* Компоненты ≡ шапка, список чатов, чат и кнопка создания чата разделены на отдельные scss/js файлы
* Реализованы страница с списком чатов и переходы между экранами списка чатов и сообщений
* Добавлена логика обновления статуса сообщений при их прочтении
* https://valvw.github.io/2024-2-VK-EDU-Frontend-V-Tuchinskaya/

![2024-10-07_190740](https://github.com/user-attachments/assets/0e565b44-ab89-4cdd-9346-b88be2a25519)

2024-10-23 16:56 UTC, martinkomitsky requested changes
Нужно исправить конфликт в гите

2024-10-23 16:56 UTC, martinkomitsky commented
@uskov-anton будут комментарии?

2024-10-29 06:32 UTC, uskov-anton reviewed
Давай актуализируем ветку дз3 относительно мастер ветки. И в целом после каждого слияния веток по дз

2024-10-29 06:36 UTC, uskov-anton commented on simple-chat/src/index.html
> +      <span class="material-icons">close</span>
Перестал работать функционал очистки сообщений - после очистки перехода к списку, а потом обратно, сообщения снова отображаются, хотя должны были быть очищены

2024-10-29 06:37 UTC, uskov-anton commented on simple-chat/src/components/chatList.js
> +                <div class="chat-last-message">${text}</div>
<img width="191" alt="Снимок экрана 2024-10-29 в 10 36 48" src="https://github.com/user-attachments/assets/4a69c110-7c30-4f7f-b1c9-f54f81a9ba1c">

Некорректное отображение, если последним в списке идет сообщение с изображением

2024-10-29 06:40 UTC, uskov-anton commented on simple-chat/src/components/chatList.js
> +    document.querySelector(".floating-button").style.display = "flex";
Фактически это дублирует стили из css. Если в процессе дальнейшей разработки в стилях что-то поменяется, то это может приводить к неожиданному поведению (порождать баги) с необходимостью последующего дебага, что снижает эффективность разработки.

Предлагаю найти решение без дублирования стилей из css

2024-10-29 06:44 UTC, uskov-anton commented on simple-chat/src/styles/chat-item.scss
> +	 display: flex;
Как-то скачет везде табуляция. Давай выровняем везде по одно линии.

2024-11-10 11:13 UTC, martinkomitsky commented
@valvw привет! очень ждём исправления

2024-11-15 09:48 UTC, martinkomitsky commented
@valvw всё еще нужно исправить конфликты

2024-11-19 14:47 UTC, martinkomitsky approved these changes
12!

2024-11-19 14:47 UTC, merged